FROM fabric8/java-alpine-openjdk11-jre:1.8

RUN apk update 
RUN apk add --no-cache --update \
    libx11 \
    apk-tools \
    busybox \
    libjpeg-turbo \
    nghttp2 \
    openssl \
    p11-kit \
    freetype \
    curl
